name: pokapon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.1
  flutter_riverpod: ^2.6.1
  confetti: ^0.8.0
  flame_audio: ^2.11.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/back.jpg
    - assets/images/gazou.jpg
    - assets/audio/panti.mp3
